### PR TITLE
Added ROOT 6 compatible scripts, minor changes in the Makefile.

### PR DESCRIPTION
**Pull request by vetlewi**
Added two new targets, normalization6 and counting6. They are both equal to normalization and counting, but outputs ROOT 6 compatible scripts (might be ROOT 5 compatible as well but is not checked). The script normalization is also fixed such that it assumes correct length of the input data in the outputted scripts.
Added a "Remove" option in the Makefile such that the "very-clean" option doesn't remove the installed
binaries.

### CODE REVIEW

**Comment by cecgresonant** [comment]
This is great, thanks Vetle! I'll try to test it ASAP.

**Comment by vetlewi** [comment]
Then Ill merge the repo!

**Comment by fzeiser** [comment]
Nice,

I'll try to test tonight or soon, too.

As I assume that they sould be compatible with root5 I would suggest to merge the changes into counting and normalization instead of having counting6 and normalization6. I guess most people will not remember to look for a counting6 binary.

@cecgresonant  What is your opinion on that?

Best,

Fabio

**Comment by vetlewi** [comment]
Well, I agree that the best solution would be to merge the changes in to the counting and normalization. I don't know if the outputted scripts will be compatible with ROOT 5 as I had to change to ROOT 6 and don't want to change again:p

If the ROOT 6 scripts are incompatible with ROOT 5 then one could add the option of either ROOT 5 or ROOT 6 script output in counting and normalization. Shouldn't be more than a line or two of code asking the user for either 5 or 6. 

Anyway, the change needed to make the scripts ROOT 6 compatible was only changing some of the "." to "->", like "gStyle.SetFillColor(0);" to "gStyle->SetFillColor(0);". I think it's because ROOT 6 is a lot more strict on notation as ROOT 5 allowed the use of "." and "->" interchangeable.

**Comment by grytveten** [comment]
The programs work fine on my mac with ROOT 5, so it seems to be compatible backwards (as one is entitled to expect). But I guess it would be good if someone else tested to before we merge into the "official" counting and normalization.

**Comment by fzeiser** [comment]
I can confirm that it works on my machine, Linux Mint (Ubuntu like), 
root 5.34.

So I'm favour for merging it now into counting and normalization.

**Pull request merged**
